version: '3'
services:
  postgres_server:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_DB=Banking_wallet
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - adminer-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres_server
    depends_on:
      - postgres_server
    networks:
      - adminer-network
      
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=12345678
      - REDIS_PORT=6379
      - REDIS_DATABASE=14
    command: redis-server --save 20 1 --loglevel warning --requirepass 12345678
    volumes:
      - redis-data:/data
    networks:
      - adminer-network
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbit-data:/var/lib/rabbitmq/
        - mq-data:/var/log/rabbitmq
    networks:
        - adminer-network

volumes:
  postgres-data:
  redis-data:
    driver: local
  rabbit-data:
    driver: local
  mq-data:
    driver: local

networks:
  adminer-network: