CREATE TABLE IF NOT EXISTS wallet_type (
    wallet_type_id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL,
    created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);